# dev
server:
  port: 8080

spring:
  datasource: # mysql8.0
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/practice_teaching_base_ems?serverTimezone=Asia/Shanghai&useUnicode=true&allowMultiQueries=true&rewriteBatchedStatements=true
    type: com.alibaba.druid.pool.DruidDataSource

  redis: # redis6.0
    database: 0 # redis数据库索引（默认为0）
    # host: 192.168.1.130 # redis服务器地址
    host: 127.0.0.1 # redis服务器地址
    port: 6379 # redis服务器端口
    # password: 123456 # redis服务器密码
    password: # redis服务器密码（本地密码默认为空）
    jedis:
      pool:
        min-idle: 0 # 连接池中的最小空闲连接
        max-idle: 200 # 连接池中的最大空闲连接
        max-active: 2000 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 10000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    timeout: 10000 # 连接超时时间（毫秒）

#  mvc:
#    # 出现错误时, 直接抛出异常(便于异常统一处理，否则捕获不到404)
#    throw-exception-if-no-handler-found: true
#  web:
#    resources:
#      # 不要为工程中的资源文件建立映射
#      add-mappings: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

# 七牛云配置
#qiniu:
#  accesskey: J004ewGSWeoJd8PWoX2rbp4YWiapdYrapS98uVOh
#  secretkey: 7zWqOPZyaYw0H1g2_48IelikMdQqPhpsRSRSvZf5
#  bucketName: djosimon
#  cdn:
#    domain: http://img.djosimon.top/
---
# prod
