# dev
server:
  port: 8080
spring:
  # mysql
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/practice_teaching_base_ems?serverTimezone=UTC&useUnicode=true&allowMultiQueries=true&rewriteBatchedStatements=true
    type: com.alibaba.druid.pool.DruidDataSource
  # redis
  redis:
    # redis数据库索引（默认为0）
    database: 0
    # redis服务器地址
    host: 192.168.1.130
    # redis服务器端口
    port: 6379
    # redis服务器密码
    password: 123456
    jedis:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 200
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
    # 连接超时时间（毫秒）Je
    timeout: 10000


#
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true

---
# prod
